In [5]:
import numpy as np
import matplotlib as plt
import pandas as pd
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

%matplotlib inline

# 데이터셋 준비
gjhousedata = pd.read_csv('광주아파트매매데이터.csv', encoding='EUC-KR')

In [3]:
!pip install seaborn # seaborn 모듈 설치

                                              0.0/293.3 kB ? eta -:--:--
     -----------------------------          225.3/293.3 kB 6.7 MB/s eta 0:00:01
     -------------------------------------- 293.3/293.3 kB 6.0 MB/s eta 0:00:00


In [6]:
gjhousedata.head()

행정명      번지    본번  부번      단지명  단지명길이  전용면적(㎡)    계약년월   계약년  계약월  \
0   광산구 도산동  1138-2  1138   2      대덕1      3  59.3100  202303  2023    3   
1   광산구 도산동     790   790   0  대주피오레1차      7  84.9800  202302  2023    2   
2   광산구 도산동     790   790   0  대주피오레1차      7  84.9800  202305  2023    5   
3   광산구 도산동     820   820   0  대주피오레2차      7  84.7575  202305  2023    5   
4   광산구 도산동     820   820   0  대주피오레2차      7  84.7575  202305  2023    5   

   계약일  거래금액(만원)   층  건축년도  건물나이            도로명  해제사유발생일  거래유형  중개사소재지  
0   18      9800   4  1990    33        송도로 143      NaN  중개거래  광주 광산구  
1    7     21000   2  2000    23    송도로182번길 55      NaN  중개거래  광주 광산구  
2   31     22350   5  2000    23    송도로182번길 55      NaN  중개거래  광주 광산구  
3    9     22400   5  2001    22  송도로182번길 16-3      NaN   직거래       -  
4   13     22000  13  2001    22  송도로182번길 16-3      NaN  중개거래  광주 광산구

In [7]:
gjhousedata.keys()

Index(['행정명', '번지', '본번', '부번', '단지명', '단지명길이', '전용면적(㎡)', '계약년월', '계약년',
       '계약월', '계약일', '거래금액(만원)', '층', '건축년도', '건물나이', '도로명', '해제사유발생일', '거래유형',
       '중개사소재지'],
      dtype='object')

In [29]:
X = gjhousedata[['단지명길이', '전용면적(㎡)', '층', '건물나이']]
y = gjhousedata['거래금액(만원)']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [19]:
# X = gjhousedata[['전용면적(㎡)', '층', '건물나이']]
# y = gjhousedata['거래금액(만원)']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [30]:
X_train.shape, y_train.shape

((297555, 4), (297555,))

In [31]:
X_test.shape, y_test.shape

((127524, 4), (127524,))

In [32]:
linear_model = LinearRegression()

In [33]:
# 모델학습
linear_model.fit(X_train, y_train)

LinearRegression()

In [34]:
# 회귀 모델의 score -> R square
linear_model.score(X_test, y_test)

0.4543721396819643

In [35]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, linear_model.predict(X_test))
r2 = r2_score(y_test,  linear_model.predict(X_test))
print(mse,r2)

84576682.69376522 0.4543721396819643


### 특성확장

In [46]:
extended_X_train = X_train.copy()

In [47]:
extended_X_train

단지명길이  전용면적(㎡)   층  건물나이
190963      2  84.9300   9    11
234550      4  59.8020  13    21
317928      4  48.4500   8    14
81061       7  59.4200  18    19
164283      2  75.8000   5    40
...       ...      ...  ..   ...
259178      7  84.9893   7     0
365838      5  84.9600  25    23
131932      6  84.9530   2     0
146867      5  84.9600   8    32
121958      2  84.5100   2    15

[297555 rows x 4 columns]

In [38]:
extended_X_test = X_test.copy()

In [44]:
extended_X_test

단지명길이   전용면적(㎡)   층  건물나이  단지명길이x단지명길이  단지명길이x전용면적(㎡)  단지명길이x층  \
351536      6   84.9831   6     4           36       509.8986       36   
245472      2   59.9900   4    12            4       119.9800        8   
257689      8   65.6043  17     1           64       524.8344      136   
103411      2   92.3900  15    18            4       184.7800       30   
416268      2   84.9900   8    16            4       169.9800       16   
...       ...       ...  ..   ...          ...            ...      ...   
5962        4   59.7600   5    16           16       239.0400       20   
334958      2   84.9600   9    25            4       169.9200       18   
62259      10   84.9931   3     6          100       849.9310       30   
32028       4   84.8858  12    13           16       339.5432       48   
320077      2  114.6230   8    14            4       229.2460       16   

        단지명길이x건물나이  전용면적(㎡)x단지명길이  전용면적(㎡)x전용면적(㎡)  전용면적(㎡)x층  전용면적(㎡)x건물나이  \
351536          24       509.8986      7222.127286   509.8986      339.9324   
245472          24       119.9800      3598.800100   239.9600      719.8800   
257689           8       524.8344      4303.924178  1115.2731       65.6043   
103411          36       184.7800      8535.912100  1385.8500     1663.0200   
416268          32       169.9800      7223.300100   679.9200     1359.8400   
...            ...            ...              ...        ...           ...   
5962            64       239.0400      3571.257600   298.8000      956.1600   
334958          50       169.9200      7218.201600   764.6400     2124.0000   
62259           60       849.9310      7223.827048   254.9793      509.9586   
32028           52       339.5432      7205.599042  1018.6296     1103.5154   
320077          28       229.2460     13138.432129   916.9840     1604.7220   

        층x단지명길이  층x전용면적(㎡)  층x층  층x건물나이  건물나이x단지명길이  건물나이x전용면적(㎡)  건물나이x층  \
351536       36   509.8986   36      24          24      339.9324      24   
245472        8   239.9600   16      48          24      719.8800      48   
257689      136  1115.2731  289      17           8       65.6043      17   
103411       30  1385.8500  225     270          36     1663.0200     270   
416268       16   679.9200   64     128          32     1359.8400     128   
...         ...        ...  ...     ...         ...           ...     ...   
5962         20   298.8000   25      80          64      956.1600      80   
334958       18   764.6400   81     225          50     2124.0000     225   
62259        30   254.9793    9      18          60      509.9586      18   
32028        48  1018.6296  144     156          52     1103.5154     156   
320077       16   916.9840   64     112          28     1604.7220     112   

        건물나이x건물나이  
351536         16  
245472        144  
257689          1  
103411        324  
416268        256  
...           ...  
5962          256  
334958        625  
62259          36  
32028         169  
320077        196  

[127524 rows x 20 columns]

In [39]:
for col1 in X_test.columns: 
    for col2 in X_test.columns: 
        extended_X_test[ col1+ 'x' + col2] = X_test[col1] * X_test[col2]

In [48]:
for col1 in X_train.columns: 
    for col2 in X_train.columns: 
        extended_X_train[ col1+ 'x' + col2] = X_train[col1] * X_train[col2]

In [40]:
X_train.head(1)

단지명길이  전용면적(㎡)  층  건물나이
190963      2    84.93  9    11

In [41]:
extended_X_test.shape # 특성 확장으로 20개 특성됨

(127524, 20)

In [49]:
extended_X_train.shape

(297555, 20)

In [50]:
# 특성 확장시킨 데이터로 새로운 모델 학습하기
linear_model2 = LinearRegression()
linear_model2.fit(extended_X_train, y_train)

LinearRegression()

In [51]:
linear_model2.score(extended_X_test, y_test)

0.47810672415717925

In [53]:
from sklearn.model_selection import cross_val_score

In [54]:
result2 = cross_val_score(linear_model2, extended_X_train, y_train, cv=5)
result2

array([0.48624291, 0.48140033, 0.47943598, 0.48731587, 0.48036756])

In [55]:
result2.mean()

0.4829525301435484

In [56]:
# 기술 통계 확인
X_train.describe()

단지명길이        전용면적(㎡)              층           건물나이
count  297555.00000  297555.000000  297555.000000  297555.000000
mean        5.41554      75.125222       8.537890      14.210922
std         2.87288      24.621100       5.424597       8.776816
min         2.00000      14.120800      -1.000000      -2.000000
25%         3.00000      59.790000       4.000000       7.000000
50%         5.00000      77.820000       8.000000      14.000000
75%         7.00000      84.941900      12.000000      21.000000
max        22.00000     283.110000      47.000000      46.000000

### scaler 적용

In [57]:
from sklearn.preprocessing import StandardScaler

In [58]:
scaler = StandardScaler()

In [59]:
scaler.fit(X_train)

StandardScaler()

In [60]:
# 데이터 스케일링 transform 함수에서 진행
transform_X_train = scaler.transform(X_train)
transform_X_train

array([[-1.18889253,  0.3982273 ,  0.08518795, -0.36584199],
       [-0.49272587, -0.62236246,  0.82257114,  0.7735253 ],
       [-0.49272587, -1.08343119, -0.09915785, -0.0240318 ],
       ...,
       [ 0.20344079,  0.39916146, -1.20523263, -1.619146  ],
       [-0.14464254,  0.39944577, -0.09915785,  2.02682931],
       [-1.18889253,  0.38116874, -1.20523263,  0.08990493]])

In [61]:
transform_X_test = scaler.transform(X_test)
transform_X_test

array([[ 0.20344079,  0.400384  , -0.46784944, -1.16339909],
       [-1.18889253, -0.61472672, -0.83654104, -0.25190526],
       [ 0.89960745, -0.38669834,  1.55995433, -1.50520927],
       ...,
       [ 1.59577411,  0.40079015, -1.02088683, -0.93552563],
       [-0.49272587,  0.39643209,  0.63822534, -0.13796853],
       [-1.18889253,  1.60422746, -0.09915785, -0.0240318 ]])

In [62]:
linear_model3 = LinearRegression()
linear_model3.fit(transform_X_train, y_train)
linear_model3.score(transform_X_test, y_test)

0.4543721396819641

In [63]:
result3 = cross_val_score(linear_model3,
                transform_X_train, y_train, cv=5)
result3

array([0.46014976, 0.45583286, 0.45471666, 0.46078299, 0.45569995])

In [64]:
result3.mean()

0.45743644401499123

### KNN에 스케일링 데이터 적용

In [65]:
from sklearn.neighbors import KNeighborsRegressor

In [66]:
# 1. 원본 데이터 (스케일링 X) - X_train
knn_model = KNeighborsRegressor() # 모델 생성
knn_result = cross_val_score(knn_model, X_train, y_train, cv=3)
knn_result

array([0.68426148, 0.68580133, 0.68756354])

In [67]:
knn_result.mean()

0.6858754515643208

In [68]:
# 2. 스케일링한 데이터 (스케일링 O) - transform_X_train
knn_model2 = KNeighborsRegressor() # 모델 생성
knn_result2 = cross_val_score(knn_model2, X_train, y_train, cv=5)
knn_result2

array([0.70578151, 0.69323056, 0.69921295, 0.70172418, 0.69662553])

In [69]:
knn_result2.mean()

0.6993149459461317